FROM node:14.11

ENV NODE_ENV development

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV HOME /app

COPY frontend/package.json /app/package.json
COPY frontend/package-lock.json /app/package-lock.json

RUN npm ci
RUN chmod 0777 /app/node_modules/

EXPOSE 3000
