version: "3.9"

services:
    db:
        image: postgres:11.8
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=kakkop-dev
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        env_file:
            - ./backend/.env
        volumes:
            - ./backend:/app
        ports:
            - 8000:8000
        depends_on:
            - db
        command: >
            sh -c "wait-for-it.sh db:5432 &&
                python manage.py migrate &&
                python manage.py init_db &&
                python manage.py runserver 0.0.0.0:8000"
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - 3000:3000
        depends_on:
            - backend
            - db
        stdin_open: true
        command: npm start
